<?php

/**
 * Copyright © 2012 - 2020 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 *
 * This file is generated by tools/build-authorization-scheme-list.php
 *
 * @package Http
 */

namespace NoreSources\Http\Authentication;

/**
 * HTTM Authenication schemes
 */
class AuthorizationScheme
{
	/**
	 * Basic HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc7617
	 */
	const BASIC = 'Basic';

	/**
	 * Bearer HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc6750
	 */
	const BEARER = 'Bearer';

	/**
	 * Digest HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc7616
	 */
	const DIGEST = 'Digest';

	/**
	 * HOBA HTTP Authorization scheme.
	 * The HOBA scheme can be used with either HTTP
	 *    servers or proxies.  When used in response to a 407 Proxy
	 *    Authentication Required indication, the appropriate proxy
	 *    authentication header fields are used instead, as with any other HTTP
	 *    authentication scheme.
	 *
	 * @see https:/ tools.ietf.org/html/rfc7486#section-3
	 */
	const HOBA = 'HOBA';

	/**
	 * Mutual HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc8120
	 */
	const MUTUAL = 'Mutual';

	/**
	 * Negotiate HTTP Authorization scheme.
	 * This authentication scheme violates both HTTP semantics (being connection-oriented) and syntax (use of syntax incompatible with the WWW-Authenticate and Authorization header field syntax).
	 *
	 * @see https:/ tools.ietf.org/html/rfc4559#section-3
	 */
	const NEGOTIATE = 'Negotiate';

	/**
	 * OAuth HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc5849#section-3.5.1
	 */
	const OAUTH = 'OAuth';

	/**
	 * SCRAM-SHA-1 HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc7804
	 */
	const SCRAM_SHA_1 = 'SCRAM-SHA-1';

	/**
	 * SCRAM-SHA-256 HTTP Authorization scheme.
	 *
	 *
	 * @see https:/ tools.ietf.org/html/rfc7804
	 */
	const SCRAM_SHA_256 = 'SCRAM-SHA-256';

	/**
	 * vapid HTTP Authorization scheme.
	 *
	 * [RFC 8292, Section 3]
	 */
	const VAPID = 'vapid';
}
