<?php

/**
 * Copyright © 2012 - 2020 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 *
 * This file is generated by tools/build-authorization-scheme-list.php
 *
 * @package Http
 */
namespace NoreSources\Http\Authentication;

use NoreSources\StringRepresentation;

/**
 * Authorization header credential data content
 */
interface CredentialDataInterface extends StringRepresentation
{
}