<?php
/**
 * Copyright © 2012 - 2020 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 */

/**
 *
 * @package Http
 */
namespace NoreSources\Http;

require (__DIR__ . '/../vendor/autoload.php');

use Nette\PhpGenerator\Dumper;
use Nette\PhpGenerator\PhpFile;
$projectPath = realPath(__DIR__ . '/..');
$sourcePath = $projectPath . '/src';

$inputDataFilePath = $projectPath . '/resources/data/perm-headers.csv';
$classFilePath = $sourcePath . '/Header/HeaderField.php';
$className = \pathinfo($classFilePath, PATHINFO_FILENAME);

$namespaceName = \implode('\\',
	[
		__NAMESPACE__,
		\str_replace('/', '\\',
			\pathinfo(\substr($classFilePath, \strlen($sourcePath) + 1), PATHINFO_DIRNAME))
	]);

$header = \file_get_contents($projectPath . '/resources/templates/class-file-header.txt');
$header = \str_replace('{year}', date('Y'), $header);

$dataStream = \fopen($inputDataFilePath, 'r');

$classFile = new PhpFile();

$classFile->addComment($header);

$ns = $classFile->addNamespace($namespaceName);

$ns->addUse('NoreSources\Container');

$classFile->addComment(
	'This file is generated by ' . \substr(__FILE__, \strlen($projectPath) + 1) . PHP_EOL);

$classFile->addComment('@package Http');

$cls = $ns->addClass($className);

$cls->addComment(<<< EOF
HTTM message header names
EOF
);

$index = 0;
while ($entry = \fgetcsv($dataStream))
{
	if ($index++ == 0)
		continue; // Column names

	$name = $entry[0];
	$protocol = $entry[2];
	$status = $entry[3];
	$references = $entry[4];

	if ($protocol != 'http')
		continue;
	if (!\in_array($status, [
		'',
		'standard'
	]))
		continue;

	$pattern = '\[RFC([0-9]+)(?:,\s*Section\s+([0-9]+(?:\.[0-9]+)*))?\]';
	$comment = \preg_replace_callback(chr(1) . $pattern . chr(1) . 'i',
		function ($m) {
			$s = 'https://tools.ietf.org/html/rfc' . $m[1];
			if (\array_key_exists(2, $m))
				$s .= '#section-' . $m[2];
			return PHP_EOL . '@see ' . $s . PHP_EOL;
		}, $references);

	$constantName = \strtoupper(\preg_replace(',[^a-zA-Z0-9],', '_', $name));
	$constantComment = $name . ' HTTP message header field name.' . PHP_EOL . PHP_EOL . $comment;

	$constant = $cls->addConstant($constantName, $name);
	$constant->addComment($constantComment);
}

\fclose($dataStream);

$dumper = new Dumper();

file_put_contents($classFilePath, $classFile);
