<?php
/**
 * Copyright © 2012 - 2020 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 */

/**
 *
 * @package Http
 */
namespace NoreSources\Http;

require (__DIR__ . '/../vendor/autoload.php');

use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Dumper;
$header = \file_get_contents(__DIR__ . '/../resources/templates/class-file-header.txt');
$header = \str_replace('{year}', date('Y'), $header);

$dataStream = \fopen(__DIR__ . '/../resources/data/http-status-codes.csv', 'r');

$classFile = new PhpFile();

$classFile->addComment($header);

/**
 *
 * @var \Nette\PhpGenerator\PhpNamespace $ns
 */
$ns = $classFile->addNamespace('NoreSources\Http');

$ns->addUse('NoreSources\Container');

$projectPath = realPath(__DIR__ . '/..');
$classFile->addComment(
	'This file is generated by ' . \substr(__FILE__, \strlen($projectPath) + 1) . PHP_EOL);

$classFile->addComment('@package Http');

/**
 *
 * @var \Nette\PhpGenerator\ClassType $cls
 */
$cls = $ns->addClass('Status');

$cls->addComment(
	'HTTP status codes.' . PHP_EOL .
	'From the Hypertext Transfer Protocol (HTTP) Status Code Registry' . PHP_EOL .
	'@see https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml');

$getStatusText = $cls->addMethod('getStatusText');
$getStatusText->setStatic(true);
$getStatusText->addParameter('code');

$statusCodes = [];

while ($entry = \fgetcsv($dataStream))
{
	$code = $entry[0];
	if (!\ctype_digit($code))
		continue;
	$code = \intval($code);
	$text = $entry[1];
	$comment = $entry[2];

	$statusCodes[$code] = $text;

	$constantName = \strtoupper(\preg_replace(',[^a-zA-Z0-9],', '_', $text));
	$constantComment = 'HTTP status code ' . $code . ' ' . $text . '.' . PHP_EOL . PHP_EOL . $comment;

	$constant = $cls->addConstant($constantName, $code);
	$constant->addComment($constantComment);
}

\fclose($dataStream);

$dumper = new Dumper();

$getStatusTextBody = 'static $statusCodes = ' . $dumper->dump($statusCodes) . ';' . PHP_EOL;
$getStatusTextBody .= 'return Container::keyValue ($statusCodes, $code, \'\');';
$getStatusText->setBody($getStatusTextBody);

file_put_contents($projectPath . '/src/Status.php', $classFile);














