<?php

/**
 * Copyright © 2021 - 2023 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 *
 * @package HTTP
 * This file is generated by tools/build-constant-files.php
 *  from http://www.iana.org/assignments/character-sets/character-sets-1.csv
 */

namespace NoreSources\Http;

/**
 * Registered charsets
 */
class Charset
{
	/**
	 * US-ASCII charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc2046
	 */
	const US_ASCII = 'US-ASCII';

	/**
	 * ISO_8859-1:1987 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_1_1987 = 'ISO_8859-1:1987';

	/**
	 * ISO_8859-2:1987 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_2_1987 = 'ISO_8859-2:1987';

	/**
	 * ISO_8859-3:1988 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_3_1988 = 'ISO_8859-3:1988';

	/**
	 * ISO_8859-4:1988 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_4_1988 = 'ISO_8859-4:1988';

	/**
	 * ISO_8859-5:1988 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_5_1988 = 'ISO_8859-5:1988';

	/**
	 * ISO_8859-6:1987 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_6_1987 = 'ISO_8859-6:1987';

	/**
	 * ISO_8859-7:1987 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1947
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_7_1987 = 'ISO_8859-7:1987';

	/**
	 * ISO_8859-8:1988 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_8_1988 = 'ISO_8859-8:1988';

	/**
	 * ISO_8859-9:1989 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_9_1989 = 'ISO_8859-9:1989';

	/**
	 * ISO-8859-10 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_10 = 'ISO-8859-10';

	/**
	 * ISO_6937-2-add charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_6937_2_ADD = 'ISO_6937-2-add';

	/**
	 * JIS_X0201 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_X0201 = 'JIS_X0201';

	/**
	 * JIS_Encoding charset name
	 */
	const JIS_ENCODING = 'JIS_Encoding';

	/**
	 * Shift_JIS charset name
	 */
	const SHIFT_JIS = 'Shift_JIS';

	/**
	 * Extended_UNIX_Code_Packed_Format_for_Japanese charset name
	 */
	const EXTENDED_UNIX_CODE_PACKED_FORMAT_FOR_JAPANESE = 'Extended_UNIX_Code_Packed_Format_for_Japanese';

	/**
	 * Extended_UNIX_Code_Fixed_Width_for_Japanese charset name
	 */
	const EXTENDED_UNIX_CODE_FIXED_WIDTH_FOR_JAPANESE = 'Extended_UNIX_Code_Fixed_Width_for_Japanese';

	/**
	 * BS_4730 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const BS_4730 = 'BS_4730';

	/**
	 * SEN_850200_C charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const SEN_850200_C = 'SEN_850200_C';

	/**
	 * IT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IT = 'IT';

	/**
	 * ES charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ES = 'ES';

	/**
	 * DIN_66003 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const DIN_66003 = 'DIN_66003';

	/**
	 * NS_4551-1 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NS_4551_1 = 'NS_4551-1';

	/**
	 * NF_Z_62-010 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NF_Z_62_010 = 'NF_Z_62-010';

	/**
	 * ISO-10646-UTF-1 charset name
	 */
	const ISO_10646_UTF_1 = 'ISO-10646-UTF-1';

	/**
	 * ISO_646.basic:1983 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_646_BASIC_1983 = 'ISO_646.basic:1983';

	/**
	 * INVARIANT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const INVARIANT = 'INVARIANT';

	/**
	 * ISO_646.irv:1983 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_646_IRV_1983 = 'ISO_646.irv:1983';

	/**
	 * NATS-SEFI charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NATS_SEFI = 'NATS-SEFI';

	/**
	 * NATS-SEFI-ADD charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NATS_SEFI_ADD = 'NATS-SEFI-ADD';

	/**
	 * NATS-DANO charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NATS_DANO = 'NATS-DANO';

	/**
	 * NATS-DANO-ADD charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NATS_DANO_ADD = 'NATS-DANO-ADD';

	/**
	 * SEN_850200_B charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const SEN_850200_B = 'SEN_850200_B';

	/**
	 * KS_C_5601-1987 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const KS_C_5601_1987 = 'KS_C_5601-1987';

	/**
	 * ISO-2022-KR charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1557
	 * [Woohyong_Choi]
	 */
	const ISO_2022_KR = 'ISO-2022-KR';

	/**
	 * EUC-KR charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1557
	 * [Woohyong_Choi]
	 */
	const EUC_KR = 'EUC-KR';

	/**
	 * ISO-2022-JP charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1468
	 * [Jun_Murai]
	 */
	const ISO_2022_JP = 'ISO-2022-JP';

	/**
	 * ISO-2022-JP-2 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1554
	 * [Masataka_Ohta]
	 */
	const ISO_2022_JP_2 = 'ISO-2022-JP-2';

	/**
	 * JIS_C6220-1969-jp charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6220_1969_JP = 'JIS_C6220-1969-jp';

	/**
	 * JIS_C6220-1969-ro charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6220_1969_RO = 'JIS_C6220-1969-ro';

	/**
	 * PT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const PT = 'PT';

	/**
	 * greek7-old charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const GREEK7_OLD = 'greek7-old';

	/**
	 * latin-greek charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const LATIN_GREEK = 'latin-greek';

	/**
	 * NF_Z_62-010_(1973) charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NF_Z_62_010__1973_ = 'NF_Z_62-010_(1973)';

	/**
	 * Latin-greek-1 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const LATIN_GREEK_1 = 'Latin-greek-1';

	/**
	 * ISO_5427 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_5427 = 'ISO_5427';

	/**
	 * JIS_C6226-1978 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6226_1978 = 'JIS_C6226-1978';

	/**
	 * BS_viewdata charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const BS_VIEWDATA = 'BS_viewdata';

	/**
	 * INIS charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const INIS = 'INIS';

	/**
	 * INIS-8 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const INIS_8 = 'INIS-8';

	/**
	 * INIS-cyrillic charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const INIS_CYRILLIC = 'INIS-cyrillic';

	/**
	 * ISO_5427:1981 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_5427_1981 = 'ISO_5427:1981';

	/**
	 * ISO_5428:1980 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_5428_1980 = 'ISO_5428:1980';

	/**
	 * GB_1988-80 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const GB_1988_80 = 'GB_1988-80';

	/**
	 * GB_2312-80 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const GB_2312_80 = 'GB_2312-80';

	/**
	 * NS_4551-2 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NS_4551_2 = 'NS_4551-2';

	/**
	 * videotex-suppl charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const VIDEOTEX_SUPPL = 'videotex-suppl';

	/**
	 * PT2 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const PT2 = 'PT2';

	/**
	 * ES2 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ES2 = 'ES2';

	/**
	 * MSZ_7795.3 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const MSZ_7795_3 = 'MSZ_7795.3';

	/**
	 * JIS_C6226-1983 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6226_1983 = 'JIS_C6226-1983';

	/**
	 * greek7 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const GREEK7 = 'greek7';

	/**
	 * ASMO_449 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ASMO_449 = 'ASMO_449';

	/**
	 * iso-ir-90 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_IR_90 = 'iso-ir-90';

	/**
	 * JIS_C6229-1984-a charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6229_1984_A = 'JIS_C6229-1984-a';

	/**
	 * JIS_C6229-1984-b charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6229_1984_B = 'JIS_C6229-1984-b';

	/**
	 * JIS_C6229-1984-b-add charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6229_1984_B_ADD = 'JIS_C6229-1984-b-add';

	/**
	 * JIS_C6229-1984-hand charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6229_1984_HAND = 'JIS_C6229-1984-hand';

	/**
	 * JIS_C6229-1984-hand-add charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6229_1984_HAND_ADD = 'JIS_C6229-1984-hand-add';

	/**
	 * JIS_C6229-1984-kana charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_C6229_1984_KANA = 'JIS_C6229-1984-kana';

	/**
	 * ISO_2033-1983 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_2033_1983 = 'ISO_2033-1983';

	/**
	 * ANSI_X3.110-1983 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ANSI_X3_110_1983 = 'ANSI_X3.110-1983';

	/**
	 * T.61-7bit charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const T_61_7BIT = 'T.61-7bit';

	/**
	 * T.61-8bit charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const T_61_8BIT = 'T.61-8bit';

	/**
	 * ECMA-cyrillic charset name
	 */
	const ECMA_CYRILLIC = 'ECMA-cyrillic';

	/**
	 * CSA_Z243.4-1985-1 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const CSA_Z243_4_1985_1 = 'CSA_Z243.4-1985-1';

	/**
	 * CSA_Z243.4-1985-2 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const CSA_Z243_4_1985_2 = 'CSA_Z243.4-1985-2';

	/**
	 * CSA_Z243.4-1985-gr charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const CSA_Z243_4_1985_GR = 'CSA_Z243.4-1985-gr';

	/**
	 * ISO_8859-6-E charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1556
	 * [IANA]
	 */
	const ISO_8859_6_E = 'ISO_8859-6-E';

	/**
	 * ISO_8859-6-I charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1556
	 * [IANA]
	 */
	const ISO_8859_6_I = 'ISO_8859-6-I';

	/**
	 * T.101-G2 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const T_101_G2 = 'T.101-G2';

	/**
	 * ISO_8859-8-E charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1556
	 * [Hank_Nussbacher]
	 */
	const ISO_8859_8_E = 'ISO_8859-8-E';

	/**
	 * ISO_8859-8-I charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1556
	 * [Hank_Nussbacher]
	 */
	const ISO_8859_8_I = 'ISO_8859-8-I';

	/**
	 * CSN_369103 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const CSN_369103 = 'CSN_369103';

	/**
	 * JUS_I.B1.002 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JUS_I_B1_002 = 'JUS_I.B1.002';

	/**
	 * IEC_P27-1 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IEC_P27_1 = 'IEC_P27-1';

	/**
	 * JUS_I.B1.003-serb charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JUS_I_B1_003_SERB = 'JUS_I.B1.003-serb';

	/**
	 * JUS_I.B1.003-mac charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JUS_I_B1_003_MAC = 'JUS_I.B1.003-mac';

	/**
	 * greek-ccitt charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const GREEK_CCITT = 'greek-ccitt';

	/**
	 * NC_NC00-10:81 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const NC_NC00_10_81 = 'NC_NC00-10:81';

	/**
	 * ISO_6937-2-25 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_6937_2_25 = 'ISO_6937-2-25';

	/**
	 * GOST_19768-74 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const GOST_19768_74 = 'GOST_19768-74';

	/**
	 * ISO_8859-supp charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_8859_SUPP = 'ISO_8859-supp';

	/**
	 * ISO_10367-box charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const ISO_10367_BOX = 'ISO_10367-box';

	/**
	 * latin-lap charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const LATIN_LAP = 'latin-lap';

	/**
	 * JIS_X0212-1990 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const JIS_X0212_1990 = 'JIS_X0212-1990';

	/**
	 * DS_2089 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const DS_2089 = 'DS_2089';

	/**
	 * us-dk charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const US_DK = 'us-dk';

	/**
	 * dk-us charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const DK_US = 'dk-us';

	/**
	 * KSC5636 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const KSC5636 = 'KSC5636';

	/**
	 * UNICODE-1-1-UTF-7 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1642
	 */
	const UNICODE_1_1_UTF_7 = 'UNICODE-1-1-UTF-7';

	/**
	 * ISO-2022-CN charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1922
	 */
	const ISO_2022_CN = 'ISO-2022-CN';

	/**
	 * ISO-2022-CN-EXT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1922
	 */
	const ISO_2022_CN_EXT = 'ISO-2022-CN-EXT';

	/**
	 * UTF-8 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc3629
	 */
	const UTF_8 = 'UTF-8';

	/**
	 * ISO-8859-13 charset name
	 */
	const ISO_8859_13 = 'ISO-8859-13';

	/**
	 * ISO-8859-14 charset name
	 */
	const ISO_8859_14 = 'ISO-8859-14';

	/**
	 * ISO-8859-15 charset name
	 */
	const ISO_8859_15 = 'ISO-8859-15';

	/**
	 * ISO-8859-16 charset name
	 */
	const ISO_8859_16 = 'ISO-8859-16';

	/**
	 * GBK charset name
	 */
	const GBK = 'GBK';

	/**
	 * GB18030 charset name
	 */
	const GB18030 = 'GB18030';

	/**
	 * OSD_EBCDIC_DF04_15 charset name
	 */
	const OSD_EBCDIC_DF04_15 = 'OSD_EBCDIC_DF04_15';

	/**
	 * OSD_EBCDIC_DF03_IRV charset name
	 */
	const OSD_EBCDIC_DF03_IRV = 'OSD_EBCDIC_DF03_IRV';

	/**
	 * OSD_EBCDIC_DF04_1 charset name
	 */
	const OSD_EBCDIC_DF04_1 = 'OSD_EBCDIC_DF04_1';

	/**
	 * ISO-11548-1 charset name
	 */
	const ISO_11548_1 = 'ISO-11548-1';

	/**
	 * KZ-1048 charset name
	 */
	const KZ_1048 = 'KZ-1048';

	/**
	 * ISO-10646-UCS-2 charset name
	 */
	const ISO_10646_UCS_2 = 'ISO-10646-UCS-2';

	/**
	 * ISO-10646-UCS-4 charset name
	 */
	const ISO_10646_UCS_4 = 'ISO-10646-UCS-4';

	/**
	 * ISO-10646-UCS-Basic charset name
	 */
	const ISO_10646_UCS_BASIC = 'ISO-10646-UCS-Basic';

	/**
	 * ISO-10646-Unicode-Latin1 charset name
	 */
	const ISO_10646_UNICODE_LATIN1 = 'ISO-10646-Unicode-Latin1';

	/**
	 * ISO-10646-J-1 charset name
	 */
	const ISO_10646_J_1 = 'ISO-10646-J-1';

	/**
	 * ISO-Unicode-IBM-1261 charset name
	 */
	const ISO_UNICODE_IBM_1261 = 'ISO-Unicode-IBM-1261';

	/**
	 * ISO-Unicode-IBM-1268 charset name
	 */
	const ISO_UNICODE_IBM_1268 = 'ISO-Unicode-IBM-1268';

	/**
	 * ISO-Unicode-IBM-1276 charset name
	 */
	const ISO_UNICODE_IBM_1276 = 'ISO-Unicode-IBM-1276';

	/**
	 * ISO-Unicode-IBM-1264 charset name
	 */
	const ISO_UNICODE_IBM_1264 = 'ISO-Unicode-IBM-1264';

	/**
	 * ISO-Unicode-IBM-1265 charset name
	 */
	const ISO_UNICODE_IBM_1265 = 'ISO-Unicode-IBM-1265';

	/**
	 * UNICODE-1-1 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1641
	 */
	const UNICODE_1_1 = 'UNICODE-1-1';

	/**
	 * SCSU charset name
	 */
	const SCSU = 'SCSU';

	/**
	 * UTF-7 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc2152
	 */
	const UTF_7 = 'UTF-7';

	/**
	 * UTF-16BE charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc2781
	 */
	const UTF_16BE = 'UTF-16BE';

	/**
	 * UTF-16LE charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc2781
	 */
	const UTF_16LE = 'UTF-16LE';

	/**
	 * UTF-16 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc2781
	 */
	const UTF_16 = 'UTF-16';

	/**
	 * CESU-8 charset name
	 *
	 * [Toby_Phipps]
	 */
	const CESU_8 = 'CESU-8';

	/**
	 * UTF-32 charset name
	 *
	 * [Mark_Davis]
	 */
	const UTF_32 = 'UTF-32';

	/**
	 * UTF-32BE charset name
	 *
	 * [Mark_Davis]
	 */
	const UTF_32BE = 'UTF-32BE';

	/**
	 * UTF-32LE charset name
	 *
	 * [Mark_Davis]
	 */
	const UTF_32LE = 'UTF-32LE';

	/**
	 * BOCU-1 charset name
	 *
	 * [Markus_Scherer]
	 */
	const BOCU_1 = 'BOCU-1';

	/**
	 * UTF-7-IMAP charset name
	 *
	 * [Florian_Weimer]
	 */
	const UTF_7_IMAP = 'UTF-7-IMAP';

	/**
	 * ISO-8859-1-Windows-3.0-Latin-1 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const ISO_8859_1_WINDOWS_3_0_LATIN_1 = 'ISO-8859-1-Windows-3.0-Latin-1';

	/**
	 * ISO-8859-1-Windows-3.1-Latin-1 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const ISO_8859_1_WINDOWS_3_1_LATIN_1 = 'ISO-8859-1-Windows-3.1-Latin-1';

	/**
	 * ISO-8859-2-Windows-Latin-2 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const ISO_8859_2_WINDOWS_LATIN_2 = 'ISO-8859-2-Windows-Latin-2';

	/**
	 * ISO-8859-9-Windows-Latin-5 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const ISO_8859_9_WINDOWS_LATIN_5 = 'ISO-8859-9-Windows-Latin-5';

	/**
	 * hp-roman8 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const HP_ROMAN8 = 'hp-roman8';

	/**
	 * Adobe-Standard-Encoding charset name
	 *
	 * [Adobe Systems Incorporated, PostScript Language Reference
	 * Manual, second edition, Addison-Wesley Publishing Company,
	 * Inc., 1990.]
	 */
	const ADOBE_STANDARD_ENCODING = 'Adobe-Standard-Encoding';

	/**
	 * Ventura-US charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const VENTURA_US = 'Ventura-US';

	/**
	 * Ventura-International charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const VENTURA_INTERNATIONAL = 'Ventura-International';

	/**
	 * DEC-MCS charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const DEC_MCS = 'DEC-MCS';

	/**
	 * IBM850 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM850 = 'IBM850';

	/**
	 * PC8-Danish-Norwegian charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const PC8_DANISH_NORWEGIAN = 'PC8-Danish-Norwegian';

	/**
	 * IBM862 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM862 = 'IBM862';

	/**
	 * PC8-Turkish charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const PC8_TURKISH = 'PC8-Turkish';

	/**
	 * IBM-Symbols charset name
	 *
	 * [IBM Corporation, "ABOUT TYPE: IBM's Technical Reference
	 * for Core Interchange Digitized Type", Publication number
	 * S544-3708-01]
	 */
	const IBM_SYMBOLS = 'IBM-Symbols';

	/**
	 * IBM-Thai charset name
	 *
	 * [IBM Corporation, "ABOUT TYPE: IBM's Technical Reference
	 * for Core Interchange Digitized Type", Publication number
	 * S544-3708-01]
	 */
	const IBM_THAI = 'IBM-Thai';

	/**
	 * HP-Legal charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const HP_LEGAL = 'HP-Legal';

	/**
	 * HP-Pi-font charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const HP_PI_FONT = 'HP-Pi-font';

	/**
	 * HP-Math8 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const HP_MATH8 = 'HP-Math8';

	/**
	 * Adobe-Symbol-Encoding charset name
	 *
	 * [Adobe Systems Incorporated, PostScript Language Reference
	 * Manual, second edition, Addison-Wesley Publishing Company,
	 * Inc., 1990.]
	 */
	const ADOBE_SYMBOL_ENCODING = 'Adobe-Symbol-Encoding';

	/**
	 * HP-DeskTop charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const HP_DESKTOP = 'HP-DeskTop';

	/**
	 * Ventura-Math charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const VENTURA_MATH = 'Ventura-Math';

	/**
	 * Microsoft-Publishing charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const MICROSOFT_PUBLISHING = 'Microsoft-Publishing';

	/**
	 * Windows-31J charset name
	 */
	const WINDOWS_31J = 'Windows-31J';

	/**
	 * GB2312 charset name
	 */
	const GB2312 = 'GB2312';

	/**
	 * Big5 charset name
	 */
	const BIG5 = 'Big5';

	/**
	 * macintosh charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const MACINTOSH = 'macintosh';

	/**
	 * IBM037 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM037 = 'IBM037';

	/**
	 * IBM038 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM038 = 'IBM038';

	/**
	 * IBM273 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM273 = 'IBM273';

	/**
	 * IBM274 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM274 = 'IBM274';

	/**
	 * IBM275 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM275 = 'IBM275';

	/**
	 * IBM277 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM277 = 'IBM277';

	/**
	 * IBM278 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM278 = 'IBM278';

	/**
	 * IBM280 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM280 = 'IBM280';

	/**
	 * IBM281 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM281 = 'IBM281';

	/**
	 * IBM284 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM284 = 'IBM284';

	/**
	 * IBM285 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM285 = 'IBM285';

	/**
	 * IBM290 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM290 = 'IBM290';

	/**
	 * IBM297 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM297 = 'IBM297';

	/**
	 * IBM420 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM420 = 'IBM420';

	/**
	 * IBM423 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM423 = 'IBM423';

	/**
	 * IBM424 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM424 = 'IBM424';

	/**
	 * IBM437 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM437 = 'IBM437';

	/**
	 * IBM500 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM500 = 'IBM500';

	/**
	 * IBM851 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM851 = 'IBM851';

	/**
	 * IBM852 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM852 = 'IBM852';

	/**
	 * IBM855 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM855 = 'IBM855';

	/**
	 * IBM857 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM857 = 'IBM857';

	/**
	 * IBM860 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM860 = 'IBM860';

	/**
	 * IBM861 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM861 = 'IBM861';

	/**
	 * IBM863 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM863 = 'IBM863';

	/**
	 * IBM864 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM864 = 'IBM864';

	/**
	 * IBM865 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM865 = 'IBM865';

	/**
	 * IBM868 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM868 = 'IBM868';

	/**
	 * IBM869 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM869 = 'IBM869';

	/**
	 * IBM870 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM870 = 'IBM870';

	/**
	 * IBM871 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM871 = 'IBM871';

	/**
	 * IBM880 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM880 = 'IBM880';

	/**
	 * IBM891 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM891 = 'IBM891';

	/**
	 * IBM903 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM903 = 'IBM903';

	/**
	 * IBM904 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM904 = 'IBM904';

	/**
	 * IBM905 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM905 = 'IBM905';

	/**
	 * IBM918 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM918 = 'IBM918';

	/**
	 * IBM1026 charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const IBM1026 = 'IBM1026';

	/**
	 * EBCDIC-AT-DE charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_AT_DE = 'EBCDIC-AT-DE';

	/**
	 * EBCDIC-AT-DE-A charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_AT_DE_A = 'EBCDIC-AT-DE-A';

	/**
	 * EBCDIC-CA-FR charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_CA_FR = 'EBCDIC-CA-FR';

	/**
	 * EBCDIC-DK-NO charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_DK_NO = 'EBCDIC-DK-NO';

	/**
	 * EBCDIC-DK-NO-A charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_DK_NO_A = 'EBCDIC-DK-NO-A';

	/**
	 * EBCDIC-FI-SE charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_FI_SE = 'EBCDIC-FI-SE';

	/**
	 * EBCDIC-FI-SE-A charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_FI_SE_A = 'EBCDIC-FI-SE-A';

	/**
	 * EBCDIC-FR charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_FR = 'EBCDIC-FR';

	/**
	 * EBCDIC-IT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_IT = 'EBCDIC-IT';

	/**
	 * EBCDIC-PT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_PT = 'EBCDIC-PT';

	/**
	 * EBCDIC-ES charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_ES = 'EBCDIC-ES';

	/**
	 * EBCDIC-ES-A charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_ES_A = 'EBCDIC-ES-A';

	/**
	 * EBCDIC-ES-S charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_ES_S = 'EBCDIC-ES-S';

	/**
	 * EBCDIC-UK charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_UK = 'EBCDIC-UK';

	/**
	 * EBCDIC-US charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const EBCDIC_US = 'EBCDIC-US';

	/**
	 * UNKNOWN-8BIT charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1428
	 */
	const UNKNOWN_8BIT = 'UNKNOWN-8BIT';

	/**
	 * MNEMONIC charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const MNEMONIC = 'MNEMONIC';

	/**
	 * MNEM charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1345
	 * [Keld_Simonsen]
	 */
	const MNEM = 'MNEM';

	/**
	 * VISCII charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1456
	 */
	const VISCII = 'VISCII';

	/**
	 * VIQR charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1456
	 */
	const VIQR = 'VIQR';

	/**
	 * KOI8-R charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc1489
	 */
	const KOI8_R = 'KOI8-R';

	/**
	 * HZ-GB-2312 charset name
	 */
	const HZ_GB_2312 = 'HZ-GB-2312';

	/**
	 * IBM866 charset name
	 *
	 * [Rick_Pond]
	 */
	const IBM866 = 'IBM866';

	/**
	 * IBM775 charset name
	 *
	 * [Hewlett-Packard Company, "HP PCL 5 Comparison Guide",
	 * (P/N 5021-0329) pp B-13, 1996.]
	 */
	const IBM775 = 'IBM775';

	/**
	 * KOI8-U charset name
	 *
	 *
	 * @see https://tools.ietf.org/html/rfc2319
	 */
	const KOI8_U = 'KOI8-U';

	/**
	 * IBM00858 charset name
	 */
	const IBM00858 = 'IBM00858';

	/**
	 * IBM00924 charset name
	 */
	const IBM00924 = 'IBM00924';

	/**
	 * IBM01140 charset name
	 */
	const IBM01140 = 'IBM01140';

	/**
	 * IBM01141 charset name
	 */
	const IBM01141 = 'IBM01141';

	/**
	 * IBM01142 charset name
	 */
	const IBM01142 = 'IBM01142';

	/**
	 * IBM01143 charset name
	 */
	const IBM01143 = 'IBM01143';

	/**
	 * IBM01144 charset name
	 */
	const IBM01144 = 'IBM01144';

	/**
	 * IBM01145 charset name
	 */
	const IBM01145 = 'IBM01145';

	/**
	 * IBM01146 charset name
	 */
	const IBM01146 = 'IBM01146';

	/**
	 * IBM01147 charset name
	 */
	const IBM01147 = 'IBM01147';

	/**
	 * IBM01148 charset name
	 */
	const IBM01148 = 'IBM01148';

	/**
	 * IBM01149 charset name
	 */
	const IBM01149 = 'IBM01149';

	/**
	 * Big5-HKSCS charset name
	 *
	 * [Nicky_Yick]
	 */
	const BIG5_HKSCS = 'Big5-HKSCS';

	/**
	 * IBM1047 charset name
	 *
	 * [Reuel_Robrigado]
	 */
	const IBM1047 = 'IBM1047';

	/**
	 * PTCP154 charset name
	 *
	 * [Alexander_Uskov]
	 */
	const PTCP154 = 'PTCP154';

	/**
	 * Amiga-1251 charset name
	 */
	const AMIGA_1251 = 'Amiga-1251';

	/**
	 * KOI7-switched charset name
	 */
	const KOI7_SWITCHED = 'KOI7-switched';

	/**
	 * BRF charset name
	 */
	const BRF = 'BRF';

	/**
	 * TSCII charset name
	 */
	const TSCII = 'TSCII';

	/**
	 * CP51932 charset name
	 */
	const CP51932 = 'CP51932';

	/**
	 * windows-874 charset name
	 */
	const WINDOWS_874 = 'windows-874';

	/**
	 * windows-1250 charset name
	 */
	const WINDOWS_1250 = 'windows-1250';

	/**
	 * windows-1251 charset name
	 */
	const WINDOWS_1251 = 'windows-1251';

	/**
	 * windows-1252 charset name
	 */
	const WINDOWS_1252 = 'windows-1252';

	/**
	 * windows-1253 charset name
	 */
	const WINDOWS_1253 = 'windows-1253';

	/**
	 * windows-1254 charset name
	 */
	const WINDOWS_1254 = 'windows-1254';

	/**
	 * windows-1255 charset name
	 */
	const WINDOWS_1255 = 'windows-1255';

	/**
	 * windows-1256 charset name
	 */
	const WINDOWS_1256 = 'windows-1256';

	/**
	 * windows-1257 charset name
	 */
	const WINDOWS_1257 = 'windows-1257';

	/**
	 * windows-1258 charset name
	 */
	const WINDOWS_1258 = 'windows-1258';

	/**
	 * TIS-620 charset name
	 */
	const TIS_620 = 'TIS-620';

	/**
	 * CP50220 charset name
	 */
	const CP50220 = 'CP50220';
}
