<?php

/**
 * Copyright © 2024 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 *
 * @package HTTP
 *          This file is generated by tools/build-constant-files.php
 *          from http://www.iana.org/assignments/http-parameters/content-coding.csv
 */
namespace NoreSources\Http\Coding;

/**
 * HTTP Content codings
 */
class ContentCoding
{

	/**
	 * aes128gcm HTTP Content coding
	 * AES-GCM encryption with a 128-bit content encryption key
	 *
	 * @see https://tools.ietf.org/html/rfc8188
	 */
	const AES128GCM = 'aes128gcm';

	/**
	 * br HTTP Content coding
	 * Brotli Compressed Data Format
	 *
	 * @see https://tools.ietf.org/html/rfc7932
	 */
	const BR = 'br';

	/**
	 * compress HTTP Content coding
	 * UNIX "compress" data format [Welch, T., "A Technique for High Performance Data Compression",
	 * IEEE Computer 17(6), June 1984.]
	 *
	 * @see https://tools.ietf.org/html/rfc9110
	 */
	const COMPRESS = 'compress';

	/**
	 * dcb HTTP Content coding
	 * "Dictionary-Compressed Brotli" data format.
	 * [RFC-ietf-httpbis-compression-dictionary-19]
	 */
	const DCB = 'dcb';

	/**
	 * dcz HTTP Content coding
	 * "Dictionary-Compressed Zstandard" data format.
	 * [RFC-ietf-httpbis-compression-dictionary-19]
	 */
	const DCZ = 'dcz';

	/**
	 * deflate HTTP Content coding
	 * "deflate" compressed data ([RFC1951]) inside the "zlib" data format ([RFC1950])
	 *
	 * @see https://tools.ietf.org/html/rfc9110
	 */
	const DEFLATE = 'deflate';

	/**
	 * exi HTTP Content coding
	 * W3C Efficient XML Interchange
	 * [W3C Recommendation: Efficient XML Interchange (EXI) Format]
	 */
	const EXI = 'exi';

	/**
	 * gzip HTTP Content coding
	 * GZIP file format [RFC1952]
	 *
	 * @see https://tools.ietf.org/html/rfc9110
	 */
	const GZIP = 'gzip';

	/**
	 * identity HTTP Content coding
	 * Reserved
	 *
	 * @see https://tools.ietf.org/html/rfc9110
	 */
	const IDENTITY = 'identity';

	/**
	 * pack200-gzip HTTP Content coding
	 * Network Transfer Format for Java Archives
	 * [JSR 200: Network Transfer Format for Java][Kumar_Srinivasan][John_Rose]
	 */
	const PACK200_GZIP = 'pack200-gzip';

	/**
	 * x-compress HTTP Content coding
	 * Deprecated (alias for compress)
	 *
	 * @see https://tools.ietf.org/html/rfc9110
	 */
	const X_COMPRESS = 'x-compress';

	/**
	 * x-gzip HTTP Content coding
	 * Deprecated (alias for gzip)
	 *
	 * @see https://tools.ietf.org/html/rfc9110
	 */
	const X_GZIP = 'x-gzip';

	/**
	 * zstd HTTP Content coding
	 * A stream of bytes compressed using the Zstandard protocol with a Window_Size of not more than
	 * 8 MB.
	 *
	 * @see https://tools.ietf.org/html/rfc9659
	 *
	 * @see https://tools.ietf.org/html/rfc8878
	 */
	const ZSTD = 'zstd';
}
